name: Update docs
on:
  push:
    branches: [master]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 1

      - name: Setup
        run: |
            sudo apt-get install python3-pip --force-yes
            sudo pip3 install toml
            sudo apt-get install gnuplot
      - name: Build
        run: |
            ./cargo_util.py --doc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            folder: doc/target/doc
            target-folder: doc
            token: ${{ secrets.RUSTGNUPLOT_PAT }}
            branch: master
            repository-name: SiegeLord/RustGnuplot
            commit-message: Automatic update from RustGnuplot
            clean: true
